Set-Location "$PSScriptRoot\.."
mvn -Dtest=TravelEasyNuovaPrenotazioneTest,TravelEasyModificaPrenotazioneTest,TravelEasyProfiloUtenteTest,TravelEasyGestionePortafoglioOreTest,TravelEasyEliminaAccountTest,TravelEasyVisualizzaPrenotazioniOperatoreTest,TravelEasyVisualizzaPrenotazioniClienteTest test
