Set-Location "$PSScriptRoot\.."
mvn -Dtest=TravelEasyNuovaPrenotazioneTest,TravelEasyProfiloUtenteTest,TravelEasyGestionePortafoglioOreTest,TravelEasyEliminaAccountTest,TravelEasyVisualizzaPrenotazioniOperatoreTest,TravelEasyVisualizzaPrenotazioniClienteTest test
